#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot emerge eselect systemctl rc-update dispatch-conf dhcpcd; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -vir" \
	mv="mv -vi" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="yt-dlp --add-metadata -i --embed-thumbnail" \
	yta="yt -x -f bestaudio/best" \
	ff="ffmpeg -hide_banner" \
	rs="rsync -vrP" \
	rsu="rs -u" \
	df="df -h" \
	dd="sudo dd status=progress" \
	sx="sxiv -a" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	s="sudo " \
	cl="clear" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="poweroff" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	y="yay" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	em="emerge --autounmask=y --autounmask-write" \
	dc="dispatch-conf" \
	ema="emaint sync -r" \
	es="eselect repository" \
	z="zathura" \
	mc="sudo mount.cifs" \
	dh="dhcpcd" \
	cr="sudo cryptsetup" \
	cdda="mpv cdda:// --cdrom-device=/dev/sr0" \
	dvd="mpv dvd:// --dvd-device=/dev/sr0" \
	bd="mpv bd:// --bluray-device=/dev/sr0" \
	ll="ls -l" \

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
